# Generated by Django 5.1.7 on 2025-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_dokuman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokuman',
            name='baslik',
        ),
        migrations.RemoveField(
            model_name='dokuman',
            name='dosya',
        ),
        migrations.AddField(
            model_name='dokuman',
            name='akim',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='arka_kapak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='ayaklar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='calisma_akimi',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='calisma_gerilimi',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='cihaz_markasi',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='cihaz_teslim_alan',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='cihaz_turu',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='demonte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='demonte_eden',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='demonte_tarih',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='devir',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='diger_olcum_degerleri',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='eksik_malzemeler',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='fan_pervane',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='fan_tasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='fircalar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='gelis_nedeni',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='gemi',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='gucu',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='ikaz_akimi',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='ikaz_voltaji',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='is_no',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='izolasyon_degerleri',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='kama',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='kasnak_kaplin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='klemens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='klemens_kapagi_kut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='komurlar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='model',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='monte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='monte_eden',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='monte_eden_tarih',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='motor_ismi',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='musteri_ismi',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='on_kapak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='parca',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='rulman_numarasi_arka',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='rulman_numarasi_on',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='rulmanlar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='saran_onaran',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='saran_onaran_tarih',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='seri_no',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='tarih',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='tersane',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='test_cihazlari',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='test_eden',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='test_eden_tarih',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='voltaj',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
