# Generated by Django 5.1.7 on 2025-03-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_dokuman_akim_alter_dokuman_calisma_akimi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokuman',
            name='yapilan_islemler',
            field=models.TextField(default='2001.01.01', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dokuman',
            name='diger_olcum_degerleri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dokuman',
            name='eksik_malzemeler',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dokuman',
            name='gelis_nedeni',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dokuman',
            name='izolasyon_degerleri',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dokuman',
            name='parca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dokuman',
            name='test_cihazlari',
            field=models.CharField(max_length=255),
        ),
    ]
