# Generated by Django 5.1.7 on 2025-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_dokuman_yapilan_islemler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokuman',
            name='demonte_tarih',
            field=models.DateField(blank=True, default='2025-01-01', null=True),
        ),
    ]
