# Generated by Django 5.1.7 on 2025-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_dokuman_demonte_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokuman',
            name='demonte_tarih',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokuman',
            name='monte_eden_tarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
