# Generated by Django 5.1.7 on 2025-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_dokuman_demonte_tarih_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokuman',
            name='saran_onaran_tarih',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokuman',
            name='tarih',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokuman',
            name='test_eden_tarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
