from django.utils.translation import gettext as _


def get_document_fields(document):
    return [
        {
            "name": "shipyard",
            "value": document.shipyard,
            "label": _("Shipyard"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "boat",
            "value": document.boat,
            "label": _("Boat"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "engine_name",
            "value": document.engine_name,
            "label": _("Engine Name"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "job_number",
            "value": document.job_number,
            "label": _("Job Number"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "customer_name",
            "value": document.customer_name,
            "label": _("Customer Name"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "date",
            "value": document.date,
            "label": _("Date"),
            "type": "date",
            "size": 4,
        },
        {
            "name": "device_receiver",
            "value": document.device_receiver,
            "label": _("Device Receiver"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "device_type",
            "value": document.device_type,
            "label": _("Device Type"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "model",
            "value": document.model,
            "label": _("Model"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "device_brand",
            "value": document.device_brand,
            "label": _("Device Brand"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "serial_number",
            "value": document.serial_number,
            "label": _("Serial Number"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "power",
            "value": document.power,
            "label": _("Power"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "current",
            "value": document.current,
            "label": _("Current"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "voltage",
            "value": document.voltage,
            "label": _("Voltage"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "rpm",
            "value": document.rpm,
            "label": _("RPM"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "warning_current",
            "value": document.warning_current,
            "label": _("Warning Current"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "warning_voltage",
            "value": document.warning_voltage,
            "label": _("Warning Voltage"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "arrival_reason",
            "value": document.arrival_reason,
            "label": _("Arrival Reason"),
            "type": "text",
            "size": 12,
        },
        {
            "name": "part",
            "value": document.part,
            "label": _("Part"),
            "type": "checkbox",
            "size": 4,
        },
        {
            "name": "mount",
            "value": document.mount,
            "label": _("Mount"),
            "type": "checkbox",
            "size": 4,
        },
        {
            "name": "dismount",
            "value": document.dismount,
            "label": _("Dismount"),
            "type": "checkbox",
            "size": 4,
        },
        {
            "name": "missing_materials",
            "value": document.missing_materials,
            "label": _("Missing Materials"),
            "type": "text",
            "size": 12,
        },
        {
            "name": "pulley_coupling",
            "value": document.pulley_coupling,
            "label": _("Pulley/Coupling"),
            "type": "checkbox",
            "size": 3,
        },
        {
            "name": "fan_carrier",
            "value": document.fan_carrier,
            "label": _("Fan Carrier"),
            "type": "checkbox",
            "size": 3,
        },
        {
            "name": "feet",
            "value": document.feet,
            "label": _("Feet"),
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "key",
            "value": document.key,
            "label": _("Key"),
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "terminal",
            "value": document.terminal,
            "label": _("Terminal"),
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "brushes",
            "value": document.brushes,
            "label": _("Brushes"),
            "type": "checkbox",
            "size": 3,
        },
        {
            "name": "terminal_cover_box",
            "value": document.terminal_cover_box,
            "label": _("Terminal Cover/Box"),
            "type": "checkbox",
            "size": 3,
        },
        {
            "name": "carbon_brushes",
            "value": document.carbon_brushes,
            "label": _("Carbon Brushes"),
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "back_cover",
            "value": document.back_cover,
            "label": _("Back Cover"),
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "fan_blade",
            "value": document.fan_blade,
            "label": _("Fan Blade"),
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "bearings",
            "value": document.bearings,
            "label": _("Bearings"),
            "type": "checkbox",
            "size": 12,
        },
        {
            "name": "front_bearing_number",
            "value": document.front_bearing_number,
            "label": _("Front Bearing Number"),
            "type": "text",
            "size": 6,
        },
        {
            "name": "back_bearing_number",
            "value": document.back_bearing_number,
            "label": _("Back Bearing Number"),
            "type": "text",
            "size": 6,
        },
        {
            "name": "dismounted_by",
            "value": document.dismounted_by,
            "label": _("Dismounted By"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "dismount_date",
            "value": document.dismount_date,
            "label": _("Dismount Date"),
            "type": "date",
            "size": 4,
        },
        {
            "name": "wrapped_repaired_by",
            "value": document.wrapped_repaired_by,
            "label": _("Wrapped/Repaired By"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "wrap_repair_date",
            "value": document.wrap_repair_date,
            "label": _("Wrap/Repair Date"),
            "type": "date",
            "size": 4,
        },
        {
            "name": "mounted_by",
            "value": document.mounted_by,
            "label": _("Mounted By"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "mount_date",
            "value": document.mount_date,
            "label": _("Mount Date"),
            "type": "date",
            "size": 4,
        },
        {
            "name": "tested_by",
            "value": document.tested_by,
            "label": _("Tested By"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "test_date",
            "value": document.test_date,
            "label": _("Test Date"),
            "type": "date",
            "size": 4,
        },
        {
            "name": "insulation_values",
            "value": document.insulation_values,
            "label": _("Insulation Values"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "operating_current",
            "value": document.operating_current,
            "label": _("Operating Current"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "operating_voltage",
            "value": document.operating_voltage,
            "label": _("Operating Voltage"),
            "type": "text",
            "size": 4,
        },
        {
            "name": "other_measurement_values",
            "value": document.other_measurement_values,
            "label": _("Other Measurement Values"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "test_devices",
            "value": document.test_devices,
            "label": _("Test Devices"),
            "type": "text",
            "size": 8,
        },
        {
            "name": "performed_operations",
            "value": document.performed_operations,
            "label": _("Performed Operations"),
            "type": "text",
            "size": 12,
        },
    ]
