def get_dokuman_fields(dokuman):
    return [
        {
            "name": "tersane",
            "value": dokuman.tersane,
            "label": "Tersane",
            "type": "text",
            "size": 4,
        },
        {
            "name": "gemi",
            "value": dokuman.gemi,
            "label": "Gemi",
            "type": "text",
            "size": 4,
        },
        {
            "name": "motor_ismi",
            "value": dokuman.motor_ismi,
            "label": "Motor İsmi",
            "type": "text",
            "size": 4,
        },
        {
            "name": "is_no",
            "value": dokuman.is_no,
            "label": "İş No",
            "type": "text",
            "size": 4,
        },
        {
            "name": "musteri_ismi",
            "value": dokuman.musteri_ismi,
            "label": "Müşteri İsmi",
            "type": "text",
            "size": 8,
        },
        {
            "name": "tarih",
            "value": dokuman.tarih,
            "label": "Tarih",
            "type": "date",
            "size": 4,
        },
        {
            "name": "cihaz_teslim_alan",
            "value": dokuman.cihaz_teslim_alan,
            "label": "Cihazı Teslim Alan",
            "type": "text",
            "size": 8,
        },
        {
            "name": "cihaz_turu",
            "value": dokuman.cihaz_turu,
            "label": "Cihaz Türü",
            "type": "text",
            "size": 8,
        },
        {
            "name": "model",
            "value": dokuman.model,
            "label": "Model",
            "type": "text",
            "size": 4,
        },
        {
            "name": "cihaz_markasi",
            "value": dokuman.cihaz_markasi,
            "label": "Cihaz Markası",
            "type": "text",
            "size": 8,
        },
        {
            "name": "seri_no",
            "value": dokuman.seri_no,
            "label": "Seri No",
            "type": "text",
            "size": 4,
        },
        {
            "name": "gucu",
            "value": dokuman.gucu,
            "label": "Gücü",
            "type": "text",
            "size": 4,
        },
        {
            "name": "akim",
            "value": dokuman.akim,
            "label": "Akım",
            "type": "text",
            "size": 4,
        },
        {
            "name": "voltaj",
            "value": dokuman.voltaj,
            "label": "Voltaj",
            "type": "text",
            "size": 4,
        },
        {
            "name": "devir",
            "value": dokuman.devir,
            "label": "Devir",
            "type": "text",
            "size": 4,
        },
        {
            "name": "ikaz_akimi",
            "value": dokuman.ikaz_akimi,
            "label": "İkaz Akımı",
            "type": "text",
            "size": 4,
        },
        {
            "name": "ikaz_voltaji",
            "value": dokuman.ikaz_voltaji,
            "label": "İkaz Voltajı",
            "type": "text",
            "size": 4,
        },
        {
            "name": "gelis_nedeni",
            "value": dokuman.gelis_nedeni,
            "label": "Geliş Nedeni",
            "type": "text",
            "size": 12,
        },
        {
            "name": "monte",
            "value": dokuman.monte,
            "label": "Monte",
            "type": "checkbox",
            "size": 4,
        },
        {
            "name": "demonte",
            "value": dokuman.demonte,
            "label": "Demonte",
            "type": "checkbox",
            "size": 4,
        },
        {
            "name": "parca",
            "value": dokuman.parca,
            "label": "Parca",
            "type": "checkbox",
            "size": 4,
        },
        {
            "name": "eksik_malzemeler",
            "value": dokuman.eksik_malzemeler,
            "label": "Eksik Malzemeler",
            "type": "text",
            "size": 12,
        },
        {
            "name": "kasnak_kaplin",
            "value": dokuman.kasnak_kaplin,
            "label": "Kasnak Kaplin",
            "type": "checkbox",
            "size": 3,
        },
        {
            "name": "fan_tasi",
            "value": dokuman.fan_tasi,
            "label": "Fan Tasi",
            "type": "checkbox",
            "size": 3,
        },
        {
            "name": "ayaklar",
            "value": dokuman.ayaklar,
            "label": "Ayaklar",
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "kama",
            "value": dokuman.kama,
            "label": "Kama",
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "klemens",
            "value": dokuman.klemens,
            "label": "Klemens",
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "fircalar",
            "value": dokuman.fircalar,
            "label": "Fircalar",
            "type": "checkbox",
            "size": 3,
        },
        {
            "name": "klemens_kapagi_kut",
            "value": dokuman.klemens_kapagi_kut,
            "label": "Klemens Kapagi Kut",
            "type": "checkbox",
            "size": 3,
        },
        {
            "name": "komurlar",
            "value": dokuman.komurlar,
            "label": "Komurlar",
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "arka_kapak",
            "value": dokuman.arka_kapak,
            "label": "Arka Kapak",
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "fan_pervane",
            "value": dokuman.fan_pervane,
            "label": "Fan Pervane",
            "type": "checkbox",
            "size": 2,
        },
        {
            "name": "rulmanlar",
            "value": dokuman.rulmanlar,
            "label": "Rulmanlar",
            "type": "checkbox",
            "size": 12,
        },
        {
            "name": "demonte_eden",
            "value": dokuman.demonte_eden,
            "label": "Demonte Eden",
            "type": "text",
            "size": 6,
        },
        {
            "name": "demonte_tarih",
            "value": dokuman.tarih,
            "label": "Demonte Tarih",
            "type": "date",
            "size": 6,
        },
        {
            "name": "monte_eden",
            "value": dokuman.monte_eden,
            "label": "Monte Eden",
            "type": "text",
            "size": 6,
        },
        {
            "name": "monte_eden_tarih",
            "value": dokuman.monte_eden_tarih,
            "label": "Monte Eden Tarih",
            "type": "date",
            "size": 6,
        },
        {
            "name": "test_eden",
            "value": dokuman.test_eden,
            "label": "Test Eden",
            "type": "text",
            "size": 6,
        },
        {
            "name": "test_eden_tarih",
            "value": dokuman.test_eden_tarih,
            "label": "Test Eden Tarih",
            "type": "date",
            "size": 6,
        },
        {
            "name": "izolasyon_degerleri",
            "value": dokuman.izolasyon_degerleri,
            "label": "İzolasyon Değerleri",
            "type": "text",
            "size": 12,
        },
        {
            "name": "calisma_akimi",
            "value": dokuman.calisma_akimi,
            "label": "Çalışma Akımı",
            "type": "text",
            "size": 6,
        },
        {
            "name": "calisma_gerilimi",
            "value": dokuman.calisma_gerilimi,
            "label": "Çalışma Gerilimi",
            "type": "text",
            "size": 6,
        },
        {
            "name": "diger_olcum_degerleri",
            "value": dokuman.diger_olcum_degerleri,
            "label": "Diğer Ölçüm Değerleri",
            "type": "text",
            "size": 12,
        },
        {
            "name": "test_cihazlari",
            "value": dokuman.test_cihazlari,
            "label": "Test Cihazları",
            "type": "text",
            "size": 12,
        },
        {
            "name": "yapilan_islemler",
            "value": dokuman.yapilan_islemler,
            "label": "Yapılan İşlemler",
            "type": "text",
            "size": 12,
        },
    ]
